input {
  tcp {
    port => 5044
    codec => json_lines   # nhận log JSON từ Spring Boot
  }
}

filter {
  # Thêm timestamp nếu chưa có
  date {
    match => ["@timestamp", "ISO8601"]
  }
  # Có thể thêm custom fields sau
}

output {
  opensearch {
    hosts => ["http://opensearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"   # index theo ngày
    user => ""      # vì đã tắt security
    password => ""
  }
  # stdout để debug Logstash
  stdout { codec => rubydebug }
}
